### PR TITLE
Fix loader_test with config

### PR DESCRIPTION
**Pull request by kostola**
### Summary

`loader_test.go` doesn't cover the case of a package with a `config` specified in its manifest and, even more, seems to fail when it's added.

This PR aims to fix all the errors and therefore improve coverage.

### Check List Before Merging

- [ ] This PR passes all pre-commit hook validations.
- [ ] This PR is fully tested and regression tests are included.
- [ ] Relevant documentation has been updated.

### CODE REVIEW

**Review by erdii — CHANGES_REQUESTED** [review]
lgtm! :heart:

Can you pls also drop the file ./testdata/Containerfile from the packageloader package?
It's unused anyways.

**Comment by kostola** [comment]
> Can you pls also drop the file ./testdata/Containerfile from the packageloader package?

@erdii done 👍

**Review by erdii — APPROVED** [review]

**Pull request merged**
