### PR TITLE
[PKO] [CLI] on-cluster tree view 

### PR DESCRIPTION
**Pull request by venkateshsredhat**
[PKO] [CLI] on-cluster tree view

https://issues.redhat.com/browse/PKO-72
[PKO] [CLI] on-cluster tree view

### Check List Before Merging

- [ ] This PR passes all pre-commit hook validations.
- [x] This PR is fully tested and regression tests are included.
- [ ] Relevant documentation has been updated.

### CODE REVIEW

**Comment by thetechnick** [comment]
LGTM from a functional perspective, code review pending :)

**Comment by erdii** [comment]
What do you think of this output format instead?

```
Kind: ClusterPackage, NamespacedName: /package-operator
├── Phase=crds
│   ├── Group=apiextensions.k8s.io/v1, Kind=CustomResourceDefinition, NamespacedName=/clusterobjectdeployments.package-operator.run
│   ├── Group=apiextensions.k8s.io/v1, Kind=CustomResourceDefinition, NamespacedName=/clusterobjectsetphases.package-operator.run
│   ├── Group=apiextensions.k8s.io/v1, Kind=CustomResourceDefinition, NamespacedName=/clusterobjectsets.package-operator.run
│   ├── Group=apiextensions.k8s.io/v1, Kind=CustomResourceDefinition, NamespacedName=/clusterobjectslices.package-operator.run
│   ├── Group=apiextensions.k8s.io/v1, Kind=CustomResourceDefinition, NamespacedName=/clusterobjecttemplates.package-operator.run
│   ├── Group=apiextensions.k8s.io/v1, Kind=CustomResourceDefinition, NamespacedName=/clusterpackages.package-operator.run
│   ├── Group=apiextensions.k8s.io/v1, Kind=CustomResourceDefinition, NamespacedName=/objectdeployments.package-operator.run
│   ├── Group=apiextensions.k8s.io/v1, Kind=CustomResourceDefinition, NamespacedName=/objectsetphases.package-operator.run
│   ├── Group=apiextensions.k8s.io/v1, Kind=CustomResourceDefinition, NamespacedName=/objectsets.package-operator.run
│   ├── Group=apiextensions.k8s.io/v1, Kind=CustomResourceDefinition, NamespacedName=/objectslices.package-operator.run
│   ├── Group=apiextensions.k8s.io/v1, Kind=CustomResourceDefinition, NamespacedName=/objecttemplates.package-operator.run
│   └── Group=apiextensions.k8s.io/v1, Kind=CustomResourceDefinition, NamespacedName=/packages.package-operator.run
├── Phase=namespace
│   └── Group=core/v1, Kind=Namespace, NamespacedName=/package-operator-system
├── Phase=rbac
│   ├── Group=rbac.authorization.k8s.io/v1, Kind=ClusterRole, NamespacedName=/package-operator-remote-phase-manager
│   ├── Group=rbac.authorization.k8s.io/v1, Kind=ClusterRoleBinding Name=/package-operator
│   ├── Group=rbac.authorization.k8s.io/v1, Kind=Role, NamespacedName=package-operator-system/package-operator
│   ├── Group=rbac.authorization.k8s.io/v1, Kind=RoleBinding, NamespacedName=package-operator-system/package-operator
│   └── Group=core/v1, Kind=ServiceAccount, NamespacedName=package-operator-system/package-operator
└── Phase=deploy
    └── apps/v1, Kind=Deployment, NamespacedName=package-operator-system/package-operator-manager
    └── Group=core/v1, Kind=Service, NamespacedName=package-operator-system/package-operator-metrics
```

Changes to the example output posted by @venkateshsredhat being:
- corrected tree nodes (the ascii art to the left)
- use consistent formatting for `Key=Value` stuff and `, ` in between multiple KV things (`Group=apiextensions.k8s.io/v1, Kind=CustomResourceDefinition`)
- use consistent field names on the output
  - `Group`, although technically `GroupVersion` would be more correct :thinking:
  - `Kind` was already there
  - `NamespacedName` in the format of `{namespace}/{name}` where `{namespace}` would be empty on global objects - like I think you already have it implemented in this PR
- the core api group is an empty string in the code but is replaced with the string `core` in many places. I think it could make sense to follow this convention.

I'm personally not too happy with having `NamespacedName=/foo` for a cluster-scoped object `foo`, but this way, the code generating this output could be the same for global and namespaced objects and consumers could also reasonably expect the field `NamespacedName` to appear for every listed object in the tree. :shrug:

**Comment by venkateshsredhat** [comment]
@erdii so the output which the cluster-tree has , basically the one I have pasted to the existing `kubectl package tree` and pasting the current output from tree command 
```shell
[ves@ves-thinkpadp1gen4i packages ]$ kubectl package tree nginx/
nginx
Package namespace/name
└── Phase deploy
    └── /v1, Kind=ConfigMap /nginx-v1
    └── apps/v1, Kind=Deployment /name-v1
```  

So based on the ticket description it made sense to follow the same pattern behind the existing tree command and this was the idea behind it .  @thetechnick  wdyt about this suggestion .

**Comment by thetechnick** [comment]
Let's keep the output consistent with the other tree command and create a follow up to revise the output of both commands.

**Comment by venkateshsredhat** [comment]
@thetechnick @erdii  I am quite unsure about the error here could any of you rerun it , running ./do Dev:Lint locally didnt give any error .

**Comment by venkateshsredhat** [comment]
@thetechnick  it would be great if you could take a look !

**Review by thetechnick — APPROVED** [review]

**Pull request merged**
